### ISSUE TITLE
Errors when using pager with react 0.13

### ISSUE THREAD

**Issue by jeffbarge** [AZaviruha/pager#1]
When using react-pager with react version 0.13.0, I get the following errors:

`Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
dist.js:38208 Warning: Pager(...): No`render`method found on the returned component instance: you may have forgotten to define`render`in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.
dist.js:18563 Warning: Don't set the props property of the component. Mutate the existing props object instead.
dist.js:24920 Uncaught TypeError: Can't add property context, object is not extensible`

I have a demo application that shows the problem. You can find it here:
https://github.com/jeffbarge/react-pager-problem

**Comment by AZaviruha** [comment]
Thank you, I'l try to fix it ASAP.

**Comment by AZaviruha** [comment]
Fixed in v1.1.1
