### ISSUE TITLE
PropTypes Deprecation Warning

### ISSUE THREAD

**Issue by McPo** [AZaviruha/pager#16]
The following warning is printed when used with react@15.5.4, however it still works fine but would be good to get it removed.

This was caused by proptypes being removed from the React core package https://facebook.github.io/react/docs/typechecking-with-proptypes.html.

>...../node_modules/fbjs/lib/warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types p

**Comment by kallaspriit** [comment]
Created a pull request. Tested on my site from my repo and seems to work well :)
https://github.com/AZaviruha/pager/pull/17

**Comment by kallaspriit** [comment]
Can You please merge the pull request?
